#! /bin/sh
##########################################################################
#    (c) Copyright 2021-2023 JRCS Ltd - All Rights Reserved              #
##########################################################################

base="/run/named"

mkdir -p ${base} ${base}/etc
mkdir -p ${base}/etc/bind ${base}/zones ${base}/var ${base}/var/run
cp -a /etc/bind/rndc.key ${base}/etc/bind
chown -R named: ${base}/zones ${base}/var
cp /usr/local/etc/named.conf ${base}/etc/bind


{
echo 'zone "." {'
echo '    type static-stub;'
echo "    server-addresses { ${HSD_MASTERS}; };"
echo "};"
} > ${base}/etc/root.inc


extra="-4"
if test "${WITH_BIND_V6}" = "Y"; then extra=""; fi

if ! named-checkconf -t ${base}
	then
		echo "======= ERROR ========"
		sleep 5
		exit 1
	fi

exec /usr/sbin/named -f ${extra} -u named -t ${base}
